owner: BritishGeologicalSurvey 
repo: inhfl-status 

sites:
  - name: INHFL GUI
    url: https://inhfl.bgs.ac.uk/
  - name: INHFL API
    url: https://inhfl-api.bgs.ac.uk/browser/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: |
      { "query": "{ __typename }" }
    expectedStatusCodes:
      - 401
  - name: INHFL Login 
    url: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_MG1sXAsVx/.well-known/openid-configuration
    method: GET
    expectedStatusCodes:
      - 200
    expectedBody:
      - '"issuer"'

status-website:
  themeUrl: https://britishgeologicalsurvey.github.io/inhfl-status/theme.css
  baseUrl: /inhfl-status
  logoUrl: https://britishgeologicalsurvey.github.io/inhfl-status/BGS-Icon-Compact-Pos-RGB.svg
  name: INHFL Status
  introTitle: "INHFL Status"
  introMessage: Live status of the INHFL Platform
  navbar:

i18n:
  locale: en-GB
