owner: BritishGeologicalSurvey 
repo: inhfl-status 

sites:
  - name: INHFL GUI UAT
    url: https://inhfl-uat.bgs.ac.uk/
  - name: INHFL GraphQL UAT
    url: https://inhfl-api-uat.bgs.ac.uk/browser/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: |
      { "query": "{ __typename }" }
    expectedStatusCodes:
      - 401

status-website:
  themeUrl: https://britishgeologicalsurvey.github.io/inhfl-status/theme.css
  baseUrl: /inhfl-status
  logoUrl: https://britishgeologicalsurvey.github.io/inhfl-status/BGS-Icon-Compact-Pos-RGB.svg
  name: INHFL Status
  introTitle: "INHFL Status"
  introMessage: Live status of the INHFL Platform
  navbar:
